### ISSUE TITLE
Allow access to original response in the middleware

### ISSUE THREAD

**Issue by gribnoysup** [mswjs/node-request-interceptor#25]
Hey y'all 👋

First of all thanks for all the hard work on this library, it's nice to see this focused, low-level approach to intercepting requests.

I think there is one feature that is currently doesn't seem to be possible to achieve with this interceptor and I'm wondering if you would be interested in looking into solving this use-case.

I was about to use this lib to monitor outgoing requests of a node.js service, and what do you know there is even an example of this in [the readme](https://github.com/mswjs/node-request-interceptor#requests-monitoring):

```js
interceptor.use((req) => {
  // Will print to stdout any outgoing requests
  // without affecting their responses
  console.log('%s %s', req.method, req.url.href)
})
```

One issue here though, it would be valuable to also be able to monitor response `statusCode` on response end, but there is no way to hook up to original response: `req` is not a real request instance, it's just normalized request options, so there is no way to attach 'response' event listener, and the second argument `ref` is the mocked response instance, not the original one (which makes sense, but doesn't help with the issue too).

Effectively if you don't want to use normalized `req` to send it yourself (and it's currently missing a bunch of `http.request` options to do it safely) there is no way (as far as I see) to intercept incoming response. If not for monitoring, I can imagine this being useful for e.g., recording and replaying functionality, where you would actually want to conditionally either bypass the interceptor if there are no recordings or respond immediately with with a record if it exists.

One idea of the top of my head is to pass the instance of the ClientRequest to the middleware handler:

```ts
export type RequestMiddleware = (
  req: InterceptedRequest,
  ref: IncomingMessage | XMLHttpRequest,
  req: http.ClientRequest,
) => ReturnedResponse | Promise<ReturnedResponse>
```

This would allow end users of the library to subscribe to `response` event that will allow them to access original response info.

I'm happy to implement it, but wanted to check first if it's something that aligns with your vision of this library and get your thoughts on the subject.

**Comment by kettanaito** [comment]
Hey, @gribnoysup! Thanks for reaching out with this.

You are right, currently there is no way to access the original response. The reason for that is the current workflow:

```
- attach patches to modules (http/https/xhr)
- catch a request instantiation (http.get/xhr.send)
- look up a middleware that returns a mocked response (this is when `interceptor.use()` is called)
- if mocked response was returned, use it as the actual response
- if mocked response was not returned, perform an actual http/https/xhr request
```

As you can see from this high-level overview, you cannot access the actual response in your middleware function, as the return statement of the middleware function decides whether to perform an original request at the first place. Overall, I think that response introspection doesn't belong to the _request_ intercepting middleware (although request middleware allows to return a mocked response... I'm open for suggestions at this point).

What we can do is to split interception into _events_:

```js
const interceptor = new RequestInterceptor()

interceptor.on('request', (req, ref) => {})
interceptor.on('response', (res) => {})
```

That way you can use the `'response'` event to log any actual/mocked responses your application makes. At that point of execution responses would be read only, as you cannot mock a response that has been sent.

> You can still technically use `ClientRequest` instance within your request middleware to perform an HTTP request. However, since at the point the `ClientRequest` instance will be patched, the requests you would make will be matched against the middleware you have (which may cause a circular dependency). 

Does that event-based interception make sense to you? How do you imagine such API, considering the lifecycle of a request?

**Comment by gribnoysup** [comment]
Thanks for such a detailed response @kettanaito! At first I really liked this ides of splitting interceptor to events, but I played around with the code to try something similar and I don't think it will cover my case? At least not in the way you are suggesting it if I understand it correctly.

So just to give a better picture of what I would like to see as a possible approach, let's look at this example of recording and replaying that I mentioned a little bit closer, I'll try to provide examples of how I would see this implemented on top of this library in current state, with events, and with `ClientRequestOverride` passed to the middleware as I suggested.

#### Record and Replay w/ Current Implementation

Will mention right away that as we discussed it is just not currently possible only with the library, but I'll add the code just for completeness

```js
const interceptor = new RequestInterceptor()
const recorded = new Map()

interceptor.use((req, ref) => {
  // As described above not possible to record in the middleware, only to return
  // previously recorded mock
  if (recorded.has(req.url)) {
    return recorded.get(req.url)
  }
})

const req = http.get('http://example.com', (res) => {
  let body = ''
  res.on('data', (chunk) => {
    body += chunk
  })
  res.on('end', () => {
    const url = `${req.getHeader('host')}${req.path}`
    recorded.set(url, { body })
  })
})
```

So even though it is kinda possible, the recording logic can't be done in the middleware, not ideal

#### Record and Replay w/ Events

Here's where it gets interesting, so on request we can still check our imaginary cache for the record. But there is a problem,
`http.IncomingMessage` doesn't have enough information for us to actually save the recording because props like [`method`](https://nodejs.org/api/http.html#http_message_method) and [`url`](https://nodejs.org/api/http.html#http_message_url) are not available there. So unless we also pass original request to this event, we can't solve the record/replay case.

```js
const interceptor = new RequestInterceptor()
const recorded = new Map()

interceptor.on('request', (req, ref) => {
  // Same as before, on request we will only check if we have the cached record,
  // nice and clean!
  if (recorded.has(req.url)) {
    return recorded.get(req.url)
  }
})

interceptor.on('response', (res) => {
  // Uh-oh! `http.IncomingMessage` doesn't have any information about request,
  // so there is no way for us to save response to the cache as we don't know
  // what was the request
})

const req = http.get('http://example.com')
```

#### Record and Replay w/ ClientRequestOverride Available in Middleware

That's the thing I proposed to do in the first comment, I'm not really set on any particular API, but basically the change would be so somehow pass an instance of ClientRequestOverride to the middleware. As you can see now in this example we can easily record and replay requests as both are in the same scope.

```js
const interceptor = new RequestInterceptor()
const recorded = new Map()

interceptor.use((req, ref, clientRequestOverrideInstance) => {
  // Again, if the recording is there, let's pass it as a mock
  if (recorded.has(req.url)) {
    return recorded.get(req.url)
  } else {
    // If it's not let's subscribe to the response event that will be fired when
    // the original response comes back
    clientRequestOverrideInstance.on('response', (res) => {
      let body = ''
      res.on('data', (chunk) => {
        body += chunk
      })
      res.on('end', () => {
        // Now we have both the request and response in one scope, so we can
        // easily match one with another and store it in the cache
        recorded.set(req.url, { body })
      })
    })
  }
})

const req = http.get('http://example.com')
```

So as far as I can see that would be almost the only approach to achieve something like what I had in mind when I opened this issue. I also fully respect the notion that this is out of scope for this library and will not be added at any point, I really appreciate the focused scope and don't have an answer if this change is still in this scope or not.

Overall it's your call if you're interested in supporting something like this in your library or not. Maybe this issue should be parked for now and you should wait a little to see if it's something that other people will request? I leave it to you how to proceed, so feel free to close the issue!

Also good point about not being able to do a real request in the middleware, I didn't thought about that and yes, indeed, this will probably not work without some additional trickery.

**Comment by kettanaito** [comment]
Like your approach on this!

Regarding events, you can still access the original request reference, because the `response` event is a _custom_ event we would know when to dispatch. Both actual and mocked responses are performed in the known context, so we can trigger any callbacks for the `response` event, and pass the `req` reference, because it's also known.

```js
// Pseudo-code, but you should get the idea
class ClientRequestOverride {
  const req = { ... } // req instance is always created

  if (mockedResponse) {
    applyResponseMiddleware(req, mockedResponse)
    respondWith(mockedResponse)
  } else {
    const req = createActualRequest()
    req.on('response', (res) => {
      applyResponseMiddleware(req, res)
    })
  }
}
```

Regarding passing the `ClientRequest` instance, I'm not sure how do you see that solved technically. As you've noticed, the `ref` does contain the `ClientRequest` reference, but it's an _override_ reference. I believe that by _actual_ reference you refer to the `ClientRequest` instance created as a part of getting the original response. Again, this leads to the middleware function being called before the original request/response could be available. 

I still lean towards the event-driven approach, as I find it more scalable and restricted (as in add a new event, than extend the existing one). That approach also seems more viable from the technical perspective, at the first glance, at least.
