### ISSUE TITLE
TypeError: Cannot read property 'URL' of null

### ISSUE THREAD

**Issue by agriffis** [mswjs/node-request-interceptor#27]
This error seems to be coming from node-request-interceptor while I'm running my tests with msw

```
(node:183) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'URL' of null
    at new XMLHttpRequest (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:113:42)
    at /app/node_modules/node-request-interceptor/lib/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.js:211:45
```

That line is marked by HERE below:

```
module.exports = function createXMLHttpRequest(window) {
  class XMLHttpRequest extends XMLHttpRequestEventTarget.interface {
    constructor() { // eslint-disable-line constructor-super
      const theThis = Object.create(new.target.prototype);
      XMLHttpRequestEventTarget.setup(theThis);
      theThis.upload = XMLHttpRequestUpload.create();
      theThis.upload._ownerDocument = window.document;

      theThis[xhrSymbols.flag] = {
        synchronous: false,
        withCredentials: false,
        mimeType: null,
        auth: null,
        method: undefined,
        responseType: "",
        requestHeaders: {},
        referrer: theThis._ownerDocument.URL,      // <----------------- HERE
        uri: "",
        timeout: 0,
        body: undefined,
        formData: false,
        preflight: false,
        requestManager: theThis._ownerDocument._requestManager,
        strictSSL: window._resourceLoader._strictSSL,
        proxy: window._resourceLoader._proxy,
        cookieJar: theThis._ownerDocument._cookieJar,
        encoding: theThis._ownerDocument._encoding,
        origin: theThis._ownerDocument.origin,
        userAgent: window.navigator.userAgent
      };
```

Is there something I should do differently to avoid this?

**Comment by kettanaito** [comment]
Hey, @agriffis! Thanks for reporting this. Please, could you answer a few questions so we could debug this issue better?

1. Which environment are you using `msw` in? (browser/Node)
1. How does your request handler looks like? (i.e. `rest.get('/user', ...)`)
1. How do you perform the request? Do you use `fetch`, or another library?

Ideally, if you set up a minimum reproduction repository that'd be awesome! Thank you.

**Comment by agriffis** [comment]
@kettanaito Thank you for the response and questions. I'm running in node with jest.

Your other two questions led to finding the problem(s):

1. My tests were globally mocking `window.fetch` to throw an error, since I was using this approach to ensure no network traffic in a previous generation of these tests.

2. My msw mocks were calling `res(...)` but not returning it.

I'm not sure which of these caused the headache, but I think I have the issues resolved now. Thanks again!

**Comment by kettanaito** [comment]
Glad to hear that the issue got resolved! 
With MSW you don't have to mock `fetch`, or other libraries anymore. I understand that migrating may take some time. Let me know if you have any other questions.
