### ISSUE TITLE
React native jest runtime

### ISSUE THREAD

**Issue by Federkun** [mswjs/node-request-interceptor#38]
Sorry about this, just an heads up on https://github.com/mswjs/node-request-interceptor/pull/37
This, while it correctly allow me to run msw on the application, it broke my tests. Apparently, while running my jest tests, the `overrideModules.native.ts` is also loaded, which is not the behaviour I was expecting.

I'll look more into this tonight.

**Comment by kettanaito** [comment]
Hey, @Federkun. Thanks for following up on this 👍

**Comment by kettanaito** [comment]
Hey 👋 How is your investigation going? Anything I can help with?

**Comment by kettanaito** [comment]
I believe this can be solved by #48. What do you think?

**Comment by Federkun** [comment]
Hi kettanaito; sorry for the absence; yep I think it's the way to go as well.
It would have been nice to have the same setup/import for both jest and rn, but the user can likely get there using jest module aliases.

If there's anything that worry me here is that both the node and the native package should expose the same api interface, as the user will use it interchangeably ( between jest and rn ) and expect the same behaviour. But it's probably okay.

**Comment by kettanaito** [comment]
That should be fine. In RN development you should use `msw/native`, while in tests `msw/node`. I find that quite straightforward, even if they promise the same API.

With the latest version (`0.5.0`) that should work already, but I haven't tested that yet.

**Comment by kettanaito** [comment]
I'm closing this, as the latest release should already cover jest runtime in React Native. Feel free to comment if you find out any unexpected behaviors. Thanks.
