### ISSUE TITLE
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by gwanduke** [mswjs/node-request-interceptor#45]
### env

- Node 14
- testing react application using msw, msw/node.

### messages

```
    TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"

      at Object.proxiedOriginalRequest (node_modules/node-request-interceptor/lib/http/override.js:55:36)
      at ClientRequestOverride.<anonymous> (node_modules/node-request-interceptor/lib/http/ClientRequest/ClientRequestOverride.js:244:39)
      at step (node_modules/node-request-interceptor/lib/http/ClientRequest/ClientRequestOverride.js:33:23)
      at Object.next (node_modules/node-request-interceptor/lib/http/ClientRequest/ClientRequestOverride.js:14:53)
      at fulfilled (node_modules/node-request-interceptor/lib/http/ClientRequest/ClientRequestOverride.js:5:58)
```

<img width="696" alt="Screen Shot 2020-08-16 at 0 57 25" src="https://user-images.githubusercontent.com/7443435/90316189-779cbc80-df5b-11ea-901a-faa32c80c803.png">

## Why this happen?

This happens when mock **https** request.

This error occurs because there is no `cert` property in `options`. 
**so `options.protocol` always set as `http:`**

https://github.com/mswjs/node-request-interceptor/blob/master/src/utils/getUrlByRequestOptions.ts#L22-L23
```js
    console.log(options); // No 'cert' property in `options` object.

    // Assume HTTPS if using an SSL certificate.
    options.protocol = options.cert ? 'https:' : DEFAULT_PROTOCOL
```

## Attachment

**`console.log(options)` result**
- using `fetch('https://...')` => log: [https-log.txt](https://github.com/mswjs/node-request-interceptor/files/5079043/https-log.txt)
- using `fetch('http://...')` => log: [http-log.txt](https://github.com/mswjs/node-request-interceptor/files/5079045/http-log.txt)

## Possible Solution

I think, `options.protocol` value should be decided by `options.uri.protocol === 'https:'`

## Example, Reproduce

https://github.com/gwanduke/example-node-request-interceptor-issue-45

App.js
```js
...
    fetch('https://example.com')
...
```

App.test.js

```js
setupServer(
  rest.get('https://example.com', (req, res, ctx) => {
    return res(
      ctx.json({})
    );
  })
);

test('render', async () => {
    render(<App />);
});
```

**Comment by gwanduke** [comment]
i had mistake

**Comment by kettanaito** [comment]
Hey, @gwanduke 👋 Could you please mention what was the root cause of this for other people to follow? Thanks.

**Comment by gwanduke** [comment]
I forget to use `listen` when using `msw` library

after write this code, it works well.
```
beforeAll(() => {
  server.listen();
});
```
(https://mswjs.io/docs/api/setup-server/listen)

I must have been mistaken while debugging yesterday.
Thanks.
