### ISSUE TITLE
NextJS: The "superCtor" argument must be of type function

### ISSUE THREAD

**Issue by dpyzo0o** [mswjs/node-request-interceptor#49]
Hi, I am using msw with nextjs and I came across an error when working on the api route. The error log points to this library so I'm here.

## Steps to reproduce
here is a minimal repo: https://github.com/dpyzo0o/next-msw-bug-demo

1. `yarn dev`,  which enables msw. Then try to click `download image`, the first time it will probably succeed (sometimes it also fails the first time). Then do a hard refresh of the page and click download image again. This time it will error out, the error message shown below points to `node-request-interceptor`

![Screen Shot 2020-08-19 at 17 16 28](https://user-images.githubusercontent.com/24768249/90616208-be323580-e23f-11ea-83dd-7663cfbe9935.png)

2. If you build the app with `yarn build && yarn start`, which basically disables msw, it will never throw this error and everything works.

I'd really appreciate it if you could help me.

**Comment by dpyzo0o** [comment]
In addition, when it errors out there is no way to restart the server-side msw. e.g. All server side mocks from msw will not work anymore, only the client-side mock will work.  I have to stop and `yarn dev` again to bring back server-side msw mock.

**Comment by dpyzo0o** [comment]
What is really strange to me is that in the api route there is nothing related to msw.

**Comment by dpyzo0o** [comment]
Any clue for a temporary fix? Currently many api routes in my project are failing when introducing msw.

**Comment by kettanaito** [comment]
I believe that @marcosvega91 has found the solution for this issue. We will ensure we don't miss anything and publish it soon.

**Comment by dpyzo0o** [comment]
Thanks for the great work!

**Comment by kettanaito** [comment]
The fix has been published in [`0.5.0`](https://github.com/mswjs/node-request-interceptor/releases/tag/v0.5.0). 

The update on the MSW side will follow, but first it needs to address #48 internally (part of https://github.com/mswjs/msw/issues/203). Please stay tuned.
