### ISSUE TITLE
Doesn't work with got.js

### ISSUE THREAD

**Issue by MikeYermolayev** [mswjs/node-request-interceptor#51]
Hello,
I'm using https://github.com/sindresorhus/got to make requests from node but looks like it doesn't work with node-request-interceptor. 
I get this errror :

![image](https://user-images.githubusercontent.com/8783498/91421103-2c898000-e85e-11ea-80e9-442779ba68da.png)

Any advices? Thanks in advance

**Comment by kettanaito** [comment]
Hey, @MikeYermolayev.

I'd kindly ask for some more context to help you solve this:

1. What version of `node-request-interceptor` are you using?
1. Please show how are you using `got` in your app.
1. Please show how are you using `node-request-interceptor` in your tests?

Also, I wonder why do you use this library directly instead of [`msw`](https://github.com/mswjs/msw)? NRI is designed to be a foundation for API mocking libraries, but is too boilerplate-y to be used directly, bear this in mind.

**Comment by MikeYermolayev** [comment]
@kettanaito sorry for a small misunderstanding. 

I was using msw but cretaed issue here since error pointed me to this library.

Already migrated to nock( 
But I was using 
`msw: 0.20.5`
`got: 11.5.2`

Example of test:
```
// status.test.js
describe(`status`, () => {
    let app;
    let restClient;

    beforeAll(async () => {
        app = await createTestApp();
        restClient = getRestClient(app.url);
    });

    it(`should get status`, async () => {
        const res = await restClient.status();

        expect(res.statusCode).toEqual(200);
        expect(res.body).toEqual({
            id: expect.any(Number),
            up: expect.any(String),
            version: expect.any(String),
            memory: {
                rss: expect.any(String),
                heapUsed: expect.any(String),
                heapTotal: expect.any(String),
            },
        });
    });

    afterAll(async () => {
        await app.destroy();
    });
});

// restClient.js
const fetch = (url, {searchParams, method = 'GET', json}) =>
    got(url, {
        responseType: 'json',
        searchParams,
        method,
        json,
        throwHttpErrors: false,
    });

export const status = () => {
    return fetch(`${url}/status`, {});
 }
```

**Comment by kettanaito** [comment]
Thanks for more details! Please, what about the `msw` usage? Could you list how you declared your request handlers/set up the library?

**Comment by MikeYermolayev** [comment]
Sorry, currently don't have any time for making repo, I'll try to do it in a few days

but I followed along https://kentcdodds.com/blog/stop-mocking-fetch and official docs of msw.
And i used es modules (maybe it can be the reason)

**Comment by kettanaito** [comment]
That's alright. The issue is most likely specific to `got` or how you use it, so it'd essential you share that information so I could help. Looking forward to that!

**Comment by kettanaito** [comment]
I believe this is related and fixed by https://github.com/mswjs/node-request-interceptor/pull/43. You don't get this fix, because `msw` hasn't updated the `node-request-interceptor` dependency yet. Please await for the next release, update `msw` in your project, and verify the issue. Thanks!

**Comment by MikeYermolayev** [comment]
Nice, thank you. Will verify it after the release and reopen the issue if it still occurs
