### ISSUE TITLE
Http protocol resolved for https module when no protocol information is provided.

### ISSUE THREAD

**Issue by sean-hernon** [mswjs/node-request-interceptor#67]
A request in the style of `require('https').request({host: 'www.banana.com', path: '/cherry'})` should be normalised to an https request, not http. I have created a pull request with a failing test and more information, so that the discussion may be continue there.

https://github.com/mswjs/node-request-interceptor/pull/66

**Comment by kettanaito** [comment]
Hey, @sean-hernon. Thank you for yet another great finding. I'll take a look at the pull request.
