### ISSUE TITLE
how to use require('node-request-interceptor')

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [mswjs/node-request-interceptor#68]
I want to use the require method to load this module. I want to use this module in electronic. What can I do.

**Comment by kettanaito** [comment]
Hey, @zhaoxiaolei519109457. 

You can use it according to the [API docs](https://github.com/mswjs/node-request-interceptor#api).

```js
const { RequestInterceptor } = require('node-request-interceptor')
const withDefaultInterceptors = require('node-request-interceptor/presets/default')

const interceptor = new RequestInterceptor(withDefaultInterceptors)
interceptor.use(req() => {
  // Provision your interception logic 
})
```

Let me know if this helps.

**Comment by zhaoxiaolei519109457** [comment]
Thank you for your reply, but it doesn't seem to be the correct answer. The following is the error reported in electro

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'node-request-interceptor/presets/default'
Require stack:
- D:\project\electron-test\main.js
- D:\project\electron-test\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\project\electron-test\main.js:20:33)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)

**Comment by kettanaito** [comment]
My bad, that's a mistake in the import path.

```diff
-node-request-interceptor/presets/default
+node-request-interceptor/lib/presets/default
```

**Comment by aprilandjan** [comment]
@kettanaito sorry to bother, but I'm having the same doubt here. I read the README file and saw that the presets are imported like: 

```js
import { interceptXMLHttpRequest } from 'node-request-interceptor/interceptors/XMLHttpRequest'
```
But the actual file is located at `<node-modules>/node-request-interceptor/lib/interceptors/XMLHttpRequest`. 

I'm using babel to transpile my ES6+ codes, and I have to use:

```js
import { interceptXMLHttpRequest } from 'node-request-interceptor/lib/interceptors/XMLHttpRequest'
```

to make it work. So is it a mistake of the README document?

**Comment by kettanaito** [comment]
Hey, @aprilandjan. Yes, that's a mistake in the README. 

The presets are located at:

```js
import withDefaultInterceptors from 'node-request-interceptor/lib/presets/default'
import { interceptClientRequest } from 'node-request-interceptor/lib/interceptors/ClientRequest'
import { interceptXMLHttpRequest } from 'node-request-interceptor/lib/interceptors/XMLHttpRequest'
```

**Comment by aprilandjan** [comment]
> Hey, @aprilandjan. Yes, that's a mistake in the README.
> 
> The presets are located at:
> 
> ```js
> import withDefaultInterceptors from 'node-request-interceptor/lib/presets/default'
> import { interceptClientRequest } from 'node-request-interceptor/lib/interceptors/ClientRequest'
> import { interceptXMLHttpRequest } from 'node-request-interceptor/lib/interceptors/XMLHttpRequest'
> ```
> 
> Please, would you be interested to submit a pull request with the fix to the README?

Thanks for the reply! I just opened https://github.com/mswjs/node-request-interceptor/pull/91 for this, please review.
