### ISSUE TITLE
Wrong response, when responseType equals "json"

### ISSUE THREAD

**Issue by sergVedmak** [mswjs/node-request-interceptor#69]
Hello

I use mock-service-worker for writing tests in my application and I faced a problem. My application use rxjs/ajax for making network request and rxjs/ajax expects xhrRequest.response to be a javascript object, when xhrRequest.responseType equals "json"(this behavior is described here https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response), but mock-service-worker, that using node-request-interceptor, returns xhrRequest.response type of string.

This behavior makes my application work differently in tests and in the browser. Is this behavior a bug in node-request-interceptor?

**Comment by kettanaito** [comment]
Hey, @sergVedmak. Thanks for reporting this.

Please give us some time to look into how we handle `responseType` and see if there's any possible issue on the library's side.

**Comment by kettanaito** [comment]
We are not respecting the `responseType` property in `XMLHttpRequest` when assigning the `response`. I find that to be an issue. Will be addressed in the nearest future.

**Comment by kettanaito** [comment]
The fix has been published in [`0.5.5`](https://github.com/mswjs/node-request-interceptor/releases/tag/v0.5.5). Could you please update and let me know that `responseType = 'json'` response is now JSON?

**Comment by sergVedmak** [comment]
@kettanaito Yes, everything works correctly. Thanks for the quick improvement!

**Comment by kettanaito** [comment]
Thank you for spotting this.
